name: "publish npm"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
      defaults:
        run:
          working-directory: ./
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm i
        - run: npm run test
        - run: npm run build
    package:
        defaults:
            run:
                working-directory: ./
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm i
            - run: npm run build
            - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
            - run: npm pack
            - name: upload
              uses: actions/upload-artifact@v2
              with:
                name: globojs
                path: .//*.tgz
    publish:
        name: "publish"
        needs: [package]
        runs-on: ubuntu-latest
        if: github.repository_owner == 'luagir94'
        steps:
        - name: upload
          uses: actions/download-artifact@v2
          with:
                name: globojs
        - uses: actions/setup-node@v1
          with:
                node-version: 20.x
                registry-url: https://npm.pkg.github.com
                scope: '@luagir94'
        - run: echo "// https://npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > ~/.npmrc
        - run: echo "_auth=${{secrets.NPM_PUBLISH_KEY}}" >> ~/.npmrc
        - run: echo "email=${{secrets.EMAIL}}" >> ~/.npmrc
        - run: echo "always-auth=true" >> ~/.npmrc
        - run: echo "${{secrets.NPM_AUTH_TOKEN}}" | npm login --registry=https://npm.pkg.github.com --scope=@luagir94 --always-auth
        - run: npm set "//npm.pkg.github.com/:_authToken=${{secrets.NPM_AUTH_TOKEN}}"
        - run: npm publish --access public $(ls *.tgz)
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}